export const ROUTES = {
  HOME: { label: 'Главная', path: '/' },
  PRIVACY: { label: 'Политика конфиденциальности', path: '/privacy-policy' },
  CONSENT: { label: 'Согласие на обработку персональных данных', path: '/data-consent' },
  CATALOG: { label: 'Каталог', path: '/catalog' },
  TSHORTS: { label: 'Футболки', path: '/catalog/tshorts' },
  CATEGORIES: { label: 'Категории', path: '/categories' },
  PRODUCTS: { label: 'Товары', path: '/products' },
  PRODUCT_CREATE: { label: 'Создание товара', path: '/products/create' },
  SIZE_CHARTS: { label: 'Таблицы размеров', path: '/size-charts' },
  PRODUCT_ATTRIBUTES: { label: 'Опции товаров', path: '/product-attributes' },
  PLATFORM_IMAGES: { label: 'Изображения платформы', path: '/platform-images' },
  HEATMAP: { label: 'Тепловая карта сайта', path: '/heatmap' },
  SUPPORT: { label: 'Обращения', path: '/support' },
  NOTIFICATIONS: { label: 'Уведомления', path: '/notifications' },
  FORMS_CALLBACK: { label: 'Форма обратной связи', path: '/forms/callback' },
} as const
